---
title: "Social Cost of Carbon"
author: "Alex Gaynor & Brendon McGovern"
subtitle: ESM 204 - Assignment 4
output:
  # pdf_document: default
  # html_document: default
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE,
                      results = FALSE)

# Setup:

rm(list=ls())

options(scipen=999) # Gives normal numbers, not scientific ones.

gc() # Cleans ram.

# Packages:

packages=c("dplyr",
           "tidyr",
           "stringr",  
           "ggplot2",
           "stargazer",
           "cowplot",
           "janitor",
           "kableExtra") 

# Fancy way to load packages (if its installed, run it, otherwise install it):

lapply(1:length(packages), 
       function(x)
         ifelse((require(packages[x],
                         character.only=TRUE)==FALSE),
                install.packages(packages[x]),
                require(packages[x],
                        character.only=TRUE)))
         
# Set directory (sets the directory where the script is saved to avoid complicated directory paths):

setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) 

getwd()
```

```{r}
# Load data (useful if letters are in the data to not let R do funny stuff):

damages <- read.csv("damages.csv", 
                            stringsAsFactors = F)

warming_import <- read.csv("warming.csv", 
                            stringsAsFactors = F)

warming_data <- warming_import %>%
  clean_names %>% 
  rename("base" ="warming_baseline", 
         "pulse" = "warming_pulse")

# Plot data:
quad_line <- function(x){
  y <- I(20000000000000*x^2) - I(3000000000000*x)
  return(y)
}


wellfare_high <- function(x){
  y <- (x/2204.62)*19.6
  z <- ((a_high-(3+y))*(demand((3+y),model_demand_high))/2)
  return(z)
  }

fit1 <- lm(damages ~ warming, 
                       data=damages)

fit2<-lm(damages~poly(warming,2,raw=TRUE), 
                       data=damages)

quadratic = fit2$coefficient[3]*damages$warming^2 + fit2$coefficient[2]*damages$warming + fit2$coefficient[1]


#Count value of sale estimation
# quadratic = fit2$coefficient[3]*Year^2 + fit2$coefficient[2]*Year + fit2$coefficient[1]
# quadratic
                      


# damages_temp <- 
  plot_1 <- ggplot(data=damages, 
                 aes(y=damages, x=warming)) +
  geom_point(aes(x=warming)) +
  theme_cowplot(16) +
  stat_smooth(aes(y = damages),
              method = "lm",
              formula = y ~ I(20000000000000*x^2) - I(3000000000000*x),
              size = 2,
              color = "orange2")
  
  plot_2 <- ggplot(data=warming_data, 
                 aes(y=quad_line(base), x=year)) +
  theme_cowplot(16) +
    stat_smooth(aes(y=quad_line(pulse)),
                color = "orange2",
                alpha = 0.8)
  

plot_1

plot_2

# +
#   stat_smooth(aes(y=quad_line(base)))
# Estimate linear model (model has an implied intercept):

ggplot(data=warming_data, 
                 aes(y=quad_line(pulse), x=year)) +
  theme_cowplot(16) +
    stat_smooth(aes(y=quad_line(pulse)),
                color = "orange2",
                alpha = 0.1) +
  stat_smooth(aes(y=quad_line(base)),
                color = "blue2",
                alpha = 0.01)
```

plot_1 <- ggplot(data=warming, 
                 aes(y=base)) +
  geom_line(aes(x=year)) +
  theme_cowplot(16) +
  (quad_line(damages$warming))

